### ISSUE TITLE
Theme color pallet is not fully displayed

### ISSUE THREAD

**Issue by Florin415** [ColorlibHQ/shotgear#1]
When we try to change the theme color, the full color pallet is not displayed : 
https://prnt.sc/uupv54

**Comment by codepixar** [comment]
Thanks @Florin415 for your query. As we are using the 'Epsilon Framework' & 'Epsilon Dashboard' library with each of our wp themes, the customizer color options and theme options are coming from there. We are just using their library with our theme. So, the bug is coming from there. So, they should update the issue by their end.

Thanks
